# Generated by Django 2.1 on 2018-08-19 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 2, 39, 48, 505545), verbose_name='publish time'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 2, 39, 48, 505170), verbose_name='publish time'),
        ),
        migrations.AddField(
            model_name='sector',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 2, 39, 48, 499811), verbose_name='publish time'),
        ),
    ]
