# Generated by Django 2.1 on 2018-08-19 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_auto_20180819_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='publish time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='publish time'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='publish time'),
        ),
    ]
