# Generated by Django 2.1 on 2018-08-19 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_auto_20180819_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish time'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish time'),
        ),
    ]
