# Generated by Django 2.1 on 2018-08-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_auto_20180819_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img_url',
            field=models.CharField(blank='True', max_length=200, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='img_url',
            field=models.CharField(blank='True', max_length=200, verbose_name='image'),
        ),
    ]
