# Generated by Django 2.1 on 2018-08-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0007_auto_20180819_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='text',
            new_name='artifact_text',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='text',
            new_name='project_text',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='text',
            new_name='sector_text',
        ),
    ]
