# Generated by Django 2.1 on 2018-08-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0008_auto_20180819_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='file_type',
            field=models.CharField(default='jpg', max_length=4),
            preserve_default=False,
        ),
    ]
